variables:
  SSH_SERVER: 'gitlab-runner@ticksift.com'
  REVIEW_DOMAIN: 'review.midnightmechanism.com'
  DEPLOY_PATH: '/var/www/ticksift'

image:
  name: lorisleiva/laravel-docker:8.1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - vendor/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - composer install
    - npm run build
  artifacts:
    paths:
      - 'public/'

.deploy:
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_KEY" | ssh-add -
  script:
    - rm -rf storage
    - ssh $SSH_SERVER "rm -rf $DEPLOY_PATH/$DEPLOY_ENV"
    - rsync -ra --exclude=.git ./ $SSH_SERVER:$DEPLOY_PATH/$DEPLOY_ENV/
    - ssh $SSH_SERVER "ln -s $DEPLOY_PATH/storage_$DEPLOY_ENV $DEPLOY_PATH/$DEPLOY_ENV/storage"
    - ssh $SSH_SERVER "php $DEPLOY_PATH/$DEPLOY_ENV/artisan storage:link"
    - ssh $SSH_SERVER "php $DEPLOY_PATH/$DEPLOY_ENV/artisan migrate --force"

deploy_review:
  stage: deploy
  before_script:
    - echo "$STAGING_DOTENV" | sed -E "s~^APP_URL=(.*)~APP_URL=$CI_ENVIRONMENT_URL/#/~g" > .env
    - !reference [.deploy, before_script]
  script:
    - rsync -a --exclude=.git --delete ./ gitlab-runner@$REVIEW_DOMAIN:/var/www/review/$CI_ENVIRONMENT_SLUG
    - ssh gitlab-runner@$REVIEW_DOMAIN "php /var/www/review/$CI_ENVIRONMENT_SLUG/artisan migrate --force"
  environment:
    name: review/$CI_PROJECT_PATH/$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    url: https://$CI_ENVIRONMENT_SLUG.$REVIEW_DOMAIN
    on_stop: stop_review
  rules:
    - if: '$CI_MERGE_REQUEST_ID'

stop_review:
  stage: deploy
  before_script:
    - !reference [.deploy, before_script]
  script:
    - ssh gitlab-runner@$REVIEW_DOMAIN "rm -rf /var/www/review/$CI_ENVIRONMENT_SLUG"
  variables:
    GIT_STRATEGY: none
  environment:
    name: review/$CI_PROJECT_PATH/$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    url: https://$CI_ENVIRONMENT_SLUG.$REVIEW_DOMAIN
    action: stop
  cache: {}
  rules:
    - if: '$CI_MERGE_REQUEST_ID'
      when: manual

deploy_staging:
  stage: deploy
  variables:
    DEPLOY_ENV: 'staging'
  before_script:
    - echo "$STAGING_DOTENV" > .env
    - !reference [.deploy, before_script]
  script:
    - !reference [.deploy, script]
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

deploy_prod:
  stage: deploy
  variables:
    DEPLOY_ENV: 'prod'
  before_script:
    - echo "$PROD_DOTENV" > .env
    - !reference [.deploy, before_script]
  script:
    - !reference [.deploy, script]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
